hash: checksum file is either one created by GNU coreutils (or compatible) or a hash-only file
hash: comparing "file-5.txt" (from command line) with "file-1.txt" (from checksum file)
hash: comparing "file-5.txt" (from command line) with "file-2.txt" (from checksum file)
hash: comparing "file-5.txt" (from command line) with "file-5.txt" (from checksum file)
hash: SHA256 checksum obtained from checksums file was:
4e7808eacba679a9d2eb8ab6eda5417ee2060919c9ebf395b052cb8241e11bdb
hash: certutil -hashfile "file-5.txt" SHA256
SHA256 hash of file-5.txt:
4e7808eacba679a9d2eb8ab6eda5417ee2060919c9ebf395b052cb8241e11bdb
CertUtil: -hashfile command completed successfully.
hash: hashes match
