hash: checksum file is either one created by GNU coreutils (or compatible) or a hash-only file
hash: comparing "file-3.txt" (from command line) with "file-1.txt" (from checksum file)
hash: comparing "file-3.txt" (from command line) with "file-2.txt" (from checksum file)
hash: comparing "file-3.txt" (from command line) with "file-5.txt" (from checksum file)
hash: missing filename in one of the lines in sha256-bad-1.txt
