hash: checksum file is either one created by GNU coreutils (or compatible) or a hash-only file
hash: comparing "..\tests\file-1.txt" (from command line) with "..\tests\file-1.txt" (from checksum file)
hash: MD5 checksum obtained from checksums file was:
3e938ccf76200b05fc1c24f8dbf88688
hash: certutil -hashfile "..\tests\file-1.txt" MD5
MD5 hash of ..\tests\file-1.txt:
3e938ccf76200b05fc1c24f8dbf88688
CertUtil: -hashfile command completed successfully.
hash: hashes match
