hash: checksum file is either one created by GNU coreutils (or compatible) or a hash-only file
hash: comparing "file with spaces.txt" (from command line) with "file with spaces.txt" (from checksum file)
hash: SHA512 checksum obtained from checksums file was:
44af5a8b6185a5b064ca99c97f1ac8a5ce77063fa6e5a8c51817fd27fe8725b4c015ca910b8a2cfce78480bf385d04ef4d8045cd306e87345b676e1ed9d8e39b
hash: certutil -hashfile "file with spaces.txt" SHA512
SHA512 hash of file with spaces.txt:
44af5a8b6185a5b064ca99c97f1ac8a5ce77063fa6e5a8c51817fd27fe8725b4c015ca910b8a2cfce78480bf385d04ef4d8045cd306e87345b676e1ed9d8e39b
CertUtil: -hashfile command completed successfully.
hash: hashes match
