hash: forced by user to treat checksum file as containing only the checksum
hash: SHA256 checksum obtained from checksums file was:
6c5d6cdb5b50602984898e1f9799ca6b22350f4a0a3a70aecda94cafea729aaa
hash: certutil -hashfile "file-1.txt" SHA256
SHA256 hash of file-1.txt:
6c5d6cdb5b50602984898e1f9799ca6b22350f4a0a3a70aecda94cafea729aaa
CertUtil: -hashfile command completed successfully.
hash: hashes match
