hash: forced by user to treat checksum file as one from the Deno repository
hash: MD5 checksum obtained from checksums file was:
22350f4a0a3a70aecda94cafea729aaa
hash: certutil -hashfile "file-1.txt" MD5
MD5 hash of file-1.txt:
3e938ccf76200b05fc1c24f8dbf88688
CertUtil: -hashfile command completed successfully.
hash: MD5 hashes do not match.
hash: actual hash is 3e938ccf76200b05fc1c24f8dbf88688
