hash: checksum file is either one created by GNU coreutils (or compatible) or a hash-only file
hash: comparing "file-3.txt" (from command line) with "file-2.txt" (from checksum file)
hash: comparing "file-3.txt" (from command line) with "file-1.txt" (from checksum file)
hash: comparing "file-3.txt" (from command line) with "file-3.txt" (from checksum file)
hash: SHA512 checksum obtained from checksums file was:
65f73af1127560436cd72e07bb4a3716cbfc92e67fad0a3249229186620ddabff5f6e14b86f6e2c9c2dd2446eea4fa7585fbb03f29fff18b2e037c4b4369374b
hash: certutil -hashfile "file-3.txt" SHA512
SHA512 hash of file-3.txt:
65f73af1127560436cd72e07bb4a3716cbfc92e67fad0a3249229186620ddabff5f6e14b86f6e2c9c2dd2446eea4fa7585fbb03f29fff18b2e037c4b4369374b
CertUtil: -hashfile command completed successfully.
hash: hashes match
